### ISSUE TITLE
ImportError: cannot import name 'OpenAI'

### ISSUE THREAD

**Issue by jakedowns** [sincethestudy/fastask#4]
```
ask --reset
Traceback (most recent call last):
  File "/usr/local/bin/ask", line 5, in <module>
    from fastask.ask import main
  File "/usr/local/lib/python3.6/dist-packages/fastask/ask.py", line 5, in <module>
    from openai import OpenAI
ImportError: cannot import name 'OpenAI'
```
`Python 3.6.9`
`pip 21.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)`
`openai                 0.8.0`
`fastask                0.2.9`
`Ubuntu 18.04.6 LTS`

**Comment by jakedowns** [comment]
trying using 
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.12
```
